# Site settings
title:       Home
email:       spjunnarkar@gmail.com
author:      Sagar Junnarkar
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://sagarjunnarkar.github.io"

# Google analytics
google_analytics: UA-50647729-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: sagarjunnarkargithubio

# Social icons
github_username: sagarjunnarkar
stackoverflow_id: 1337996
twitter_username: sagarjunnarkar
google_plus_id:
linkedin_username: sagar-j-98488218
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
paginate_path: "/blogs/page:num/"
sass:
  compressed: true
gems:
  - jekyll-sitemap
plugins: [jekyll-paginate]
